// Conversión entre los objetos camelCase que usa la app y las filas
// snake_case de Postgres (supabase/migrations/0001_init.sql). Cada
// repositorio en services/db/repositories usa esto para espejar sus
// escrituras contra Supabase — ver services/db/repositories/base.ts.
import type {
  AvailabilitySettings,
  EventItem,
  Grade,
  Semester,
  StudySession,
  Subject,
} from '@/types/domain'

export const semesterMapper = {
  toRow: (r: Semester, userId: string) => ({
    id: r.id,
    user_id: userId,
    name: r.name,
    start_date: r.startDate,
    end_date: r.endDate,
    is_archived: r.isArchived,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): Semester => ({
    id: row.id,
    name: row.name,
    startDate: row.start_date,
    endDate: row.end_date,
    isArchived: row.is_archived,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}

export const subjectMapper = {
  toRow: (r: Subject, userId: string) => ({
    id: r.id,
    user_id: userId,
    semester_id: r.semesterId,
    name: r.name,
    professor: r.professors,
    schedule: r.schedule,
    location: r.location,
    color: r.color,
    description: r.description,
    difficulty: r.difficulty,
    weekly_hours_target: r.weeklyHoursTarget,
    status: r.status,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): Subject => ({
    id: row.id,
    semesterId: row.semester_id,
    name: row.name,
    professors: row.professor ?? [],
    schedule: row.schedule,
    location: row.location,
    color: row.color,
    description: row.description,
    difficulty: row.difficulty,
    weeklyHoursTarget: row.weekly_hours_target,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}

export const eventMapper = {
  toRow: (r: EventItem, userId: string) => ({
    id: r.id,
    user_id: userId,
    subject_id: r.subjectId,
    type: r.type,
    title: r.title,
    date: r.date,
    time: r.time,
    topics: r.topics,
    importance: r.importance,
    notes: r.notes,
    status: r.status,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): EventItem => ({
    id: row.id,
    subjectId: row.subject_id,
    type: row.type,
    title: row.title,
    date: row.date,
    time: row.time,
    topics: row.topics,
    importance: row.importance,
    notes: row.notes,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}

export const sessionMapper = {
  toRow: (r: StudySession, userId: string) => ({
    id: r.id,
    user_id: userId,
    subject_id: r.subjectId,
    event_id: r.eventId,
    chat_message_id: r.chatMessageId,
    topic: r.topic,
    objective: r.objective,
    date: r.date,
    duration_minutes: r.durationMinutes,
    priority: r.priority,
    status: r.status,
    origin: r.origin,
    reasoning: r.reasoning,
    actual_minutes: r.actualMinutes,
    focus_rating: r.focusRating,
    perceived_difficulty: r.perceivedDifficulty,
    notes: r.notes,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): StudySession => ({
    id: row.id,
    subjectId: row.subject_id,
    eventId: row.event_id,
    chatMessageId: row.chat_message_id,
    topic: row.topic,
    objective: row.objective,
    date: row.date,
    durationMinutes: row.duration_minutes,
    priority: Number(row.priority),
    status: row.status,
    origin: row.origin,
    reasoning: row.reasoning,
    actualMinutes: row.actual_minutes,
    focusRating: row.focus_rating,
    perceivedDifficulty: row.perceived_difficulty,
    notes: row.notes,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}

export const gradeMapper = {
  toRow: (r: Grade, userId: string) => ({
    id: r.id,
    user_id: userId,
    subject_id: r.subjectId,
    name: r.name,
    score: r.score,
    max_score: r.maxScore,
    weight: r.weight,
    date: r.date,
    observations: r.observations,
    status: r.status,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): Grade => ({
    id: row.id,
    subjectId: row.subject_id,
    name: row.name,
    score: row.score === null ? null : Number(row.score),
    maxScore: Number(row.max_score),
    weight: Number(row.weight),
    date: row.date,
    observations: row.observations,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}

export const availabilityMapper = {
  // Sin "id": es un singleton por usuario, se hace upsert por user_id
  // (ver availability.ts) para no pisarse con el id local fijo "default".
  toRow: (r: AvailabilitySettings, userId: string) => ({
    user_id: userId,
    max_daily_minutes: r.maxDailyMinutes,
    preferred_session_minutes: r.preferredSessionMinutes,
    break_minutes: r.breakMinutes,
    time_of_day_preference: r.timeOfDayPreference,
    weekly_slots: r.weeklySlots,
    exceptions: r.exceptions,
    created_at: r.createdAt,
    updated_at: r.updatedAt,
    deleted_at: r.deletedAt,
  }),
  fromRow: (row: any): AvailabilitySettings => ({
    id: 'default',
    maxDailyMinutes: row.max_daily_minutes,
    preferredSessionMinutes: row.preferred_session_minutes,
    breakMinutes: row.break_minutes,
    timeOfDayPreference: row.time_of_day_preference,
    weeklySlots: row.weekly_slots ?? [],
    exceptions: row.exceptions ?? [],
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  }),
}
